[package]
name = "protocol-artifacts"
version = "0.1.1"
license = "Apache-2.0"
edition = "2021"

[dependencies]
protocol-types = { path = "../types" }
sha2 = { workspace = true }
tokio = { workspace = true }
mime_guess = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }